### ISSUE TITLE
亿点建议

### ISSUE THREAD

**Issue by Sanluli36li** [shenjackyuanjie/Minecraft_Science_Tree#6]
这里应该是`N/3单元`而不是`N/3村` 因为本质上还是一个村庄，和1.13以前的堆叠村庄概念不一样  
我觉得叫`多单元刷铁机`比较合适  
![image](https://user-images.githubusercontent.com/5201743/138448483-7e1142ea-ca28-42ff-9d20-dcdd6cc01e89.png)
  
这里应该漏了一个返回门刷沙机  
动能刷沙机是在主世界末地门专门应对黑曜石平台刷新的变种  
![image](https://user-images.githubusercontent.com/5201743/138449148-d5dd656f-6914-4534-ac73-48b3f2ffe045.png)
  
基于气泡柱？  
![image](https://user-images.githubusercontent.com/5201743/138449710-54262c85-9be4-473e-bdc6-695e5afc80bb.png)
  
交易为啥是方块资源处理？  
![image](https://user-images.githubusercontent.com/5201743/138449849-1d446baf-c564-4dfa-b7d2-e7130c45b507.png)

**整个刷怪塔部分都很奇怪，有的按归中思路分 有的按击杀方式分**
。。。
![image](https://user-images.githubusercontent.com/5201743/138451163-0ac22416-ebae-4625-9ebe-ef142032d672.png)

应该分为`双维度`和`仇恨吸引`两种思路
![image](https://user-images.githubusercontent.com/5201743/138451029-f1c38569-b76f-4c03-aa23-30df4c2c4036.png)

这部分是不是应该并入`生物资源获取`
![image](https://user-images.githubusercontent.com/5201743/138451605-908412bf-e72b-41df-8e7c-92b359de3598.png)

有点冗余的感觉
![image](https://user-images.githubusercontent.com/5201743/138451736-558e8ceb-5d65-43f6-b5e9-1b0aedb351e9.png)

假人应该不算科技
![image](https://user-images.githubusercontent.com/5201743/138451792-64538a67-5186-44cc-a9bd-6c7938232230.png)

TNT复制应该属于`方块资源处理`而不是`资源复制`
![image](https://user-images.githubusercontent.com/5201743/138451955-09d2b9b9-d28e-4116-be51-8de566a7427e.png)

`全物品分类`不是科技，而是物品分类技术的结合应用
![image](https://user-images.githubusercontent.com/5201743/138452160-94afa0cc-1fd8-47c1-b809-1e24249c8145.png)

箱子矿车震怒
![image](https://user-images.githubusercontent.com/5201743/138452377-2879ca52-50bd-4535-ae20-92b022f9540b.png)

fallen建议以思路代替具体型号  
除树场部分外：
1.2 石材部分牛奶百万刷石机指重点是爆炸室 本质上还是带重组刷石机器 玄武岩同理  
而且挖石机是不是应该并到上面圆石分类里  
![image](https://user-images.githubusercontent.com/5201743/138450063-c5f51613-9c06-42fd-a4bd-f083b3d4bd94.png)

**Comment by shenjackyuanjie** [comment]
done
