### ISSUE TITLE
1.20科技树更新

### ISSUE THREAD

**Issue by LYOfficial** [shenjackyuanjie/Minecraft_Science_Tree#7]
1.20新增
* 4.18 [基于嗅探兽的火把花农场农场](https://www.bilibili.com/video/BV1iM4y1f7Wn)
* 4.18 粉红色花簇农场
* 4.18 瓶子草荚果农场
* 1.1.1 樱花木农场

**Comment by shenjackyuanjie** [comment]
麻烦帮忙加一下cce和oome的更新抑制器？（）

**Comment by LYOfficial** [comment]
> 

how?

**Comment by shenjackyuanjie** [comment]
我想起来了（
我tm回来啦！

**Comment by LYOfficial** [comment]
蚌

**Comment by shenjackyuanjie** [comment]
ok 都更新完了（
